# === Application Name ===
spring.application.name=youtube-video-summarizer

# === Database Configuration ===
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://shortline.proxy.rlwy.net:33464/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:cLkwmqjncDDMuVbhqOQvlWtLKzoFiNoZ}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Fix
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# === Server Port ===
server.port=8080

# Hikari Fix
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.keepalive-time=30000
spring.datasource.hikari.connection-test-query=SELECT 1

# === Email Config ===
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sg6640770@gmail.com
spring.mail.password=pcfhpyylifmfijbd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com