# === Application Name ===
spring.application.name=youtube-video-summarizer

# === Database Configuration ===
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://autorack.proxy.rlwy.net:42573/railway}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:rZvEcBJnUMorNFrRRiCsxEogIeclShNu}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA Fix
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


# === Server Port ===
server.port=8080

# === HikariCP ===
spring.datasource.hikari.max-lifetime=180000
spring.datasource.hikari.idle-timeout=120000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.keepalive-time=60000
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.connection-test-query=SELECT 1

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=sg6640770@gmail.com
spring.mail.password=pcfhpyylifmfijbd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

mail.host=smtp.gmail.com
mail.port=465
mail.username=${spring.mail.username}
mail.password=${spring.mail.password}